name: Manual ECS Deployment DEV

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'ECR Image tag to deploy (e.g., 1a2b3c4)'
        required: true
        type: string

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 515308131221.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: baymeters/company_website
  ECS_CLUSTER: arn:aws:ecs:us-east-1:515308131221:cluster/company_website_runner
  ECS_SERVICE: website-runner-service-test
  ECS_TASK_DEFINITION: baymeter-website-test
  CONTAINER_NAME: baymeter-website-container

jobs:
  deploy-to-ecs:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION }} --query taskDefinition > task-definition.json

      - name: Update ECS task definition with new image
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.event.inputs.image_tag }}

      - name: Deploy to Amazon ECS
        run: |
          SERVICE_NAME=${{ env.ECS_SERVICE }}
          CLUSTER_NAME=$(echo ${{ env.ECS_CLUSTER }} | awk -F'/' '{print $NF}')
          
          # Check if the service exists
          if aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME --query "services[?status=='ACTIVE']" --output text | grep -q $SERVICE_NAME; then
            echo "Updating existing service: $SERVICE_NAME"
            aws ecs update-service \
              --cluster ${{ env.ECS_CLUSTER }} \
              --service $SERVICE_NAME \
              --task-definition ${{ steps.task-def.outputs.task-definition }} \
              --force-new-deployment
          else
            echo "Creating new service: $SERVICE_NAME"
            aws ecs create-service \
              --cluster ${{ env.ECS_CLUSTER }} \
              --service-name $SERVICE_NAME \
              --task-definition ${{ steps.task-def.outputs.task-definition }} \
              --desired-count 1 \
              --launch-type FARGATE \
              --network-configuration "awsvpcConfiguration={subnets=[subnet-12345678,subnet-87654321],securityGroups=[sg-12345678]}" \
              --wait-for-service-stability
          fi

      - name: Print deployment info
        run: |
          echo "Deployed image ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.event.inputs.image_tag }} to ECS"
          echo "Cluster: ${{ env.ECS_CLUSTER }}"
          echo "Service: $SERVICE_NAME"
